package com.zseltzer.zevadditions.init;

import com.zseltzer.zevadditions.Reference;
import com.zseltzer.zevadditions.RegisterHelper;
import com.zseltzer.zevadditions.blocks.ZevBlockStairs;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;

public class ModStairs 
{	
		//I know I can do this much more easily with a for loop and an array, but I couldn't get it to work so for now, I have this.
	
	public static Block adobeBlockStairs = new ZevBlockStairs(ModBlocks.adobeBlock, "adobeBlock");
	public static Block adobe_bricksStairs = new ZevBlockStairs(ModBlocks.adobe_bricks, "adobe_bricks");
	public static Block adobeTileStairs = new ZevBlockStairs(ModBlocks.adobeTile, "adobeTile");
	public static Block amethystBlockStairs = new ZevBlockStairs(ModBlocks.amethystBlock, "amethystBlock");
	public static Block amethystOreStairs = new ZevBlockStairs(ModBlocks.amethystOre, "amethystOre");
	public static Block andesiteStairs = new ZevBlockStairs(ModBlocks.andesite, "andesite");
	public static Block andesite_bricksStairs = new ZevBlockStairs(ModBlocks.andesite_bricks, "andesite_bricks");
	public static Block andesite_smoothStairs = new ZevBlockStairs(ModBlocks.andesite_smooth, "andesite_smooth");
	public static Block aquamarineBlockStairs = new ZevBlockStairs(ModBlocks.aquamarineBlock, "aquamarineBlock"); 
	public static Block aquaStoneStairs = new ZevBlockStairs(ModBlocks.aquaStone, "aquaStone");
	public static Block aquaStone_smoothStairs = new ZevBlockStairs(ModBlocks.aquaStone_smooth, "aquaStone_smooth");
	public static Block ashBlockStairs = new ZevBlockStairs(ModBlocks.ashBlock, "ashBlock");
	public static Block ashStoneStairs = new ZevBlockStairs(ModBlocks.ashStone, "ashStone");
	public static Block bambooThatchBlockStairs = new ZevBlockStairs(ModBlocks.bambooThatchBlock, "bambooThatchBlock");
	public static Block basaltStairs = new ZevBlockStairs(ModBlocks.basalt, "basalt");
	public static Block basalt_bricksStairs = new ZevBlockStairs(ModBlocks.basalt_bricks, "basalt_bricks");
	public static Block basalt_smoothStairs = new ZevBlockStairs(ModBlocks.basalt_smooth, "basalt_smooth");
	public static Block bedrockStairs = new ZevBlockStairs(Blocks.bedrock, "bedrock");
	public static Block blazeBlockStairs = new ZevBlockStairs(ModBlocks.blazeBlock, "blazeBlock");
	public static Block blueStoneStairs = new ZevBlockStairs(ModBlocks.blueStone, "blueStone");
	public static Block blueStone_smoothStairs = new ZevBlockStairs(ModBlocks.blueStone_smooth, "blueStone_smooth");
	public static Block bonemealBlockStairs = new ZevBlockStairs(ModBlocks.bonemealBlock, "bonemealBlock");
	public static Block boneBlockStairs = new ZevBlockStairs(ModBlocks.boneBlock, "boneBlock");
	public static Block brownStoneStairs = new ZevBlockStairs(ModBlocks.brownStone, "brownStone");
	public static Block brownStone_smoothStairs = new ZevBlockStairs(ModBlocks.brownStone_smooth, "brownStone_smooth");
	public static Block cementBlockStairs = new ZevBlockStairs(ModBlocks.cementBlock, "cementBlock");
	public static Block charcoalBlockStairs = new ZevBlockStairs(ModBlocks.charcoalBlock, "charcoalBlock");
	public static Block chertStairs = new ZevBlockStairs(ModBlocks.chert, "chert");
	public static Block chert_bricksStairs = new ZevBlockStairs(ModBlocks.chert_bricks, "chert_bricks");
	public static Block chertPolishedBlockStairs = new ZevBlockStairs(ModBlocks.chertPolishedBlock, "chertPolishedBlock");
	public static Block chertCobbleStairs = new ZevBlockStairs(ModBlocks.chertCobble, "chertCobble");
	public static Block clayStairs = new ZevBlockStairs(Blocks.clay, "clay");
	public static Block coalBlockStairs = new ZevBlockStairs(Blocks.coal_block, "coalBlock");
	public static Block coarseDirtStairs = new ZevBlockStairs(ModBlocks.coarseDirt, "coarseDirt");
	public static Block crackedSandStairs = new ZevBlockStairs(ModBlocks.crackedSand, "crackedSand");
	public static Block cragRockStairs = new ZevBlockStairs(ModBlocks.cragRock, "cragRock");
	public static Block daciteStairs = new ZevBlockStairs(ModBlocks.dacite, "dacite");
	public static Block dacite_bricksStairs = new ZevBlockStairs(ModBlocks.dacite_bricks, "dacite_bricks");
	public static Block dacitePolishedBlockStairs = new ZevBlockStairs(ModBlocks.dacitePolishedBlock, "dacitePolishedBlock");
	public static Block daciteCobbleStairs = new ZevBlockStairs(ModBlocks.daciteCobble, "daciteCobble");
	public static Block darkPrismarineStairs = new ZevBlockStairs(ModBlocks.darkPrismarine, "darkPrismarine");
	public static Block darkQuartzBlockStairs = new ZevBlockStairs(ModBlocks.darkQuartzBlock, "darkQuartzBlock");
	public static Block diamondBlockStairs = new ZevBlockStairs(Blocks.diamond_block, "diamondBlock");
	public static Block diamondOreStairs = new ZevBlockStairs(Blocks.diamond_ore, "diamondOre");
	public static Block dioriteStairs = new ZevBlockStairs(ModBlocks.diorite, "diorite");
	public static Block diorite_bricksStairs = new ZevBlockStairs(ModBlocks.diorite_bricks, "diorite_bricks");
	public static Block diorite_smoothStairs = new ZevBlockStairs(ModBlocks.diorite_smooth, "diorite_smooth");
	public static Block dirtStairs = new ZevBlockStairs(Blocks.dirt, "dirt");
	public static Block driedDirtStairs = new ZevBlockStairs(ModBlocks.driedDirt, "driedDirt");
	public static Block emeraldBlockStairs = new ZevBlockStairs(Blocks.emerald_block, "emeraldBlock");
	public static Block emeraldOreStairs = new ZevBlockStairs(Blocks.emerald_ore, "emeraldOre");
	public static Block enderPearlBlockStairs = new ZevBlockStairs(ModBlocks.enderPearlBlock, "enderPearlBlock");
	public static Block endStoneStairs = new ZevBlockStairs(Blocks.end_stone, "endStone");
	public static Block endStoneBricksStairs = new ZevBlockStairs(ModBlocks.endStoneBricks, "endStoneBricks");
	public static Block flintBlockStairs = new ZevBlockStairs(ModBlocks.flintBlock, "flintBlock");
	public static Block gabbroStairs = new ZevBlockStairs(ModBlocks.gabbro, "gabbro");
	public static Block gabbro_bricksStairs = new ZevBlockStairs(ModBlocks.gabbro_bricks, "gabbro_bricks");
	public static Block gabbroPolishedBlockStairs = new ZevBlockStairs(ModBlocks.gabbroPolishedBlock, "gabbroPolishedBlock");
	public static Block gabbroCobbleStairs = new ZevBlockStairs(ModBlocks.gabbroCobble, "gabbroCobble");
	public static Block glowstoneStairs = new ZevBlockStairs(Blocks.glowstone, "glowstone");
	public static Block goldBlockStairs = new ZevBlockStairs(Blocks.gold_block, "goldBlock");
	public static Block goldOreStairs = new ZevBlockStairs(Blocks.gold_ore, "goldOre");
	public static Block graniteStairs = new ZevBlockStairs(ModBlocks.granite, "granite");
	public static Block granite_bricksStairs = new ZevBlockStairs(ModBlocks.granite_bricks, "granite_bricks");
	public static Block granite_smoothStairs = new ZevBlockStairs(ModBlocks.granite_smooth, "granite_smooth");
	public static Block graniteCobbleStairs = new ZevBlockStairs(ModBlocks.graniteCobble, "graniteCobble");
	public static Block gravelStairs = new ZevBlockStairs(Blocks.gravel, "gravel");
	public static Block greenStoneStairs = new ZevBlockStairs(ModBlocks.greenStone, "greenStone");
	public static Block greenStone_smoothStairs = new ZevBlockStairs(ModBlocks.greenStone_smooth, "greenStone_smooth");
	public static Block gunpowderBlockStairs = new ZevBlockStairs(ModBlocks.gunpowderBlock, "gunpowderBlock");
	public static Block hardenedClayStairs = new ZevBlockStairs(Blocks.hardened_clay, "hardenedClay");
	public static Block hardenedDirtStairs = new ZevBlockStairs(ModBlocks.hardenedDirt, "hardenedDirt");
	public static Block hardenedSandStairs = new ZevBlockStairs(ModBlocks.hardenedSand, "hardenedSand");
	public static Block hardenedSandstoneStairs = new ZevBlockStairs(ModBlocks.hardenedSandstone, "hardenedSandstone");
	public static Block hardenedSandstone_bricksStairs = new ZevBlockStairs(ModBlocks.hardenedSandstone_bricks, "hardenedSandstone_bricks");
	public static Block hardenedSandstoneCobbleStairs = new ZevBlockStairs(ModBlocks.hardenedSandstoneCobble, "hardenedSandstoneCobble");
	public static Block hardenedSandstonePolishedBlockStairs = new ZevBlockStairs(ModBlocks.hardenedSandstonePolishedBlock, "hardenedSandstonePolishedBlock");
	public static Block hardenedIceStairs = new ZevBlockStairs(ModBlocks.hardenedIce, "hardenedIce");
	public static Block hayVariantStairs = new ZevBlockStairs(ModBlocks.hayVariant, "hayVariant");
	public static Block ironBlockStairs = new ZevBlockStairs(Blocks.iron_block, "ironBlock");
	public static Block ironOreStairs = new ZevBlockStairs(Blocks.iron_ore, "ironOre");
	public static Block lapisBlockStairs = new ZevBlockStairs(Blocks.lapis_block, "lapisBlock");
	public static Block lapisOreStairs = new ZevBlockStairs(Blocks.lapis_ore, "lapisOre");
	public static Block limestoneStairs = new ZevBlockStairs(ModBlocks.limestone, "limestone");
	public static Block limestone_bricksStairs = new ZevBlockStairs(ModBlocks.limestone_bricks, "limestone_bricks");
	public static Block limestoneCobbleStairs = new ZevBlockStairs(ModBlocks.limestoneCobble, "limestoneCobble");
	public static Block limestonePolishedBlockStairs = new ZevBlockStairs(ModBlocks.limestonePolishedBlock, "limestonePolishedBlock");
	public static Block magmaBlockStairs = new ZevBlockStairs(ModBlocks.magmaBlock, "magmaBlock");
    public static Block marbleStairs = new ZevBlockStairs(ModBlocks.marble, "marble");
	public static Block marble_bricksStairs = new ZevBlockStairs(ModBlocks.marble_bricks, "marble_bricks");
	public static Block marblePolishedBlockStairs = new ZevBlockStairs(ModBlocks.marblePolishedBlock, "marblePolishedBlock");
	public static Block marbleCobbleStairs = new ZevBlockStairs(ModBlocks.marbleCobble, "marbleCobble");
	public static Block melonBlockStairs = new ZevBlockStairs(Blocks.melon_block, "melon_block");
	public static Block mudBlockStairs = new ZevBlockStairs(ModBlocks.mudBlock, "mudBlock");
	public static Block mud_bricksStairs = new ZevBlockStairs(ModBlocks.mud_bricks, "mud_bricks");
	public static Block mushroomBlock1Stairs = new ZevBlockStairs(Blocks.brown_mushroom_block, "mushroomBlock1").setBlockTextureName(Reference.MODID + ":mushroomBlock1");
	public static Block mushroomBlock2Stairs = new ZevBlockStairs(Blocks.brown_mushroom_block, "mushroomBlock2").setBlockTextureName(Reference.MODID + ":mushroomBlock2");
	public static Block mushroomBlock3Stairs = new ZevBlockStairs(Blocks.red_mushroom_block, "mushroomBlock3").setBlockTextureName(Reference.MODID + ":mushroomBlock3");
	public static Block mushroomBlock4Stairs = new ZevBlockStairs(Blocks.red_mushroom_block, "mushroomBlock4").setBlockTextureName(Reference.MODID + ":mushroomBlock4");
	public static Block netherrackStairs = new ZevBlockStairs(Blocks.netherrack, "netherrack");
	public static Block netherWartBlockStairs = new ZevBlockStairs(ModBlocks.netherWartBlock, "netherWartBlock");
	public static Block obsidianStairs = new ZevBlockStairs(Blocks.obsidian, "obsidian");
	public static Block obsidian_smoothStairs = new ZevBlockStairs(ModBlocks.obsidian_smooth, "obsidian_smooth");
	public static Block packedIceStairs = new ZevBlockStairs(Blocks.packed_ice, "packedIce");
	public static Block pinkStoneStairs = new ZevBlockStairs(ModBlocks.pinkStone, "pinkStone");
	public static Block pinkStone_smoothStairs = new ZevBlockStairs(ModBlocks.pinkStone_smooth, "pinkStone_smooth");
	public static Block prismarine_bricksStairs = new ZevBlockStairs(ModBlocks.prismarine_bricks, "prismarine_bricks");
	public static Block quartzStoneStairs = new ZevBlockStairs(ModBlocks.quartzStone, "quartzStone");
	public static Block quartzStone_bricksStairs = new ZevBlockStairs(ModBlocks.quartzStone_bricks, "quartzStone_bricks");
	public static Block quartzStonePolishedBlockStairs = new ZevBlockStairs(ModBlocks.quartzStonePolishedBlock, "quartzStonePolishedBlock");
	public static Block quartzStoneCobbleStairs = new ZevBlockStairs(ModBlocks.quartzStoneCobble, "quartzStoneCobble");
	public static Block quickSandStairs = new ZevBlockStairs(ModBlocks.quickSand, "quickSand");
	public static Block redNetherBrickStairs = new ZevBlockStairs(ModBlocks.redNetherBrick, "redNetherBrick");
	public static Block redRockStairs = new ZevBlockStairs(ModBlocks.redRock, "redRock");
	public static Block redRock_bricksStairs = new ZevBlockStairs(ModBlocks.redRock_bricks, "redRock_bricks");
	public static Block redRockCobbleStairs = new ZevBlockStairs(ModBlocks.redRockCobble, "redRockCobble");
	public static Block redRockTileStairs = new ZevBlockStairs(ModBlocks.redRockTile, "redRockTile");
	public static Block redstoneBlockStairs = new ZevBlockStairs(Blocks.redstone_block, "redstone_block");
	public static Block rhyoliteStairs = new ZevBlockStairs(ModBlocks.rhyolite, "rhyolite");
	public static Block rhyolite_bricksStairs = new ZevBlockStairs(ModBlocks.rhyolite_bricks, "rhyolite_bricks");
	public static Block rhyolitePolishedBlockStairs = new ZevBlockStairs(ModBlocks.rhyolitePolishedBlock, "rhyolitePolishedBlock");
	public static Block rhyoliteCobbleStairs = new ZevBlockStairs(ModBlocks.rhyoliteCobble, "rhyoliteCobble");
	public static Block rottenFleshBlockStairs = new ZevBlockStairs(ModBlocks.rottenFleshBlock, "rottenFleshBlock");
	public static Block rubyBlockStairs = new ZevBlockStairs(ModBlocks.rubyBlock, "rubyBlock");
	public static Block rubyOreStairs = new ZevBlockStairs(ModBlocks.rubyOre, "rubyOre");
	public static Block sandCoarseDirtStairs = new ZevBlockStairs(ModBlocks.sandCoarseDirt, "sandCoarseDirt");
	public static Block sandDirtStairs = new ZevBlockStairs(ModBlocks.sandDirt, "sandDirt");
	public static Block sapphireBlockStairs = new ZevBlockStairs(ModBlocks.sapphireBlock, "sapphireBlock");
	public static Block sapphireOreStairs = new ZevBlockStairs(ModBlocks.sapphireOre, "sapphireOre");
	public static Block schistStairs = new ZevBlockStairs(ModBlocks.schist, "schist");
	public static Block schist_bricksStairs = new ZevBlockStairs(ModBlocks.schist_bricks, "schist_bricks");
	public static Block schistCobbleStairs = new ZevBlockStairs(ModBlocks.schistCobble, "schistCobble");
	public static Block schistPolishedBlockStairs = new ZevBlockStairs(ModBlocks.schistPolishedBlock, "schistPolishedBlock");
	public static Block shaleStairs = new ZevBlockStairs(ModBlocks.shale, "shale");
	public static Block shale_bricksStairs = new ZevBlockStairs(ModBlocks.shale_bricks, "shale_bricks");
	public static Block shalePolishedBlockStairs = new ZevBlockStairs(ModBlocks.shalePolishedBlock, "shalePolishedBlock");
	public static Block shaleCobbleStairs = new ZevBlockStairs(ModBlocks.shaleCobble, "shaleCobble");
	public static Block shale_smoothStairs = new ZevBlockStairs(ModBlocks.shale_smooth, "shale_smooth");
	public static Block siltStoneStairs = new ZevBlockStairs(ModBlocks.siltStone, "siltStone");
	public static Block siltStone_smoothStairs = new ZevBlockStairs(ModBlocks.siltStone_smooth, "siltStone_smooth");
	public static Block silverBlockStairs = new ZevBlockStairs(ModBlocks.silverBlock, "silverBlock");
	public static Block silverOreStairs = new ZevBlockStairs(ModBlocks.silverOre, "silverOre");
	public static Block slateStairs = new ZevBlockStairs(ModBlocks.slate, "slate");
	public static Block slate_bricksStairs = new ZevBlockStairs(ModBlocks.slate_bricks, "slate_bricks");
	public static Block slateCobbleStairs = new ZevBlockStairs(ModBlocks.slateCobble, "slateCobble");
	public static Block smoothStoneStairs = new ZevBlockStairs(Blocks.stone, "smoothStone");
	public static Block snowStairs = new ZevBlockStairs(Blocks.snow, "snow");
	public static Block soulSandStairs = new ZevBlockStairs(Blocks.soul_sand, "soul_sand");
	public static Block spongeStairs = new ZevBlockStairs(Blocks.sponge, "sponge");
	public static Block stoneChalkStairs = new ZevBlockStairs(ModBlocks.stoneChalk, "stoneChalk");
	public static Block stoneChalk_bricksStairs = new ZevBlockStairs(ModBlocks.stoneChalk_bricks, "stoneChalk_bricks");
	public static Block stoneChalkPolishedBlockStairs = new ZevBlockStairs(ModBlocks.stoneChalkPolishedBlock, "stoneChalkPolishedBlock");
	public static Block stoneChalkCobbleStairs = new ZevBlockStairs(ModBlocks.stoneChalkCobble, "stoneChalkCobble");
    public static Block stone1Stairs = new ZevBlockStairs(ModBlocks.stone1, "stone1");
	public static Block stone2Stairs = new ZevBlockStairs(ModBlocks.stone2, "stone2");
	public static Block stone3Stairs = new ZevBlockStairs(ModBlocks.stone3, "stone3");
	public static Block stone4Stairs = new ZevBlockStairs(ModBlocks.stone4, "stone4");
	public static Block stone5Stairs = new ZevBlockStairs(ModBlocks.stone5, "stone5");
	public static Block stone6Stairs = new ZevBlockStairs(ModBlocks.stone6, "stone6");
	public static Block stone7Stairs = new ZevBlockStairs(ModBlocks.stone7, "stone7");
	public static Block stone8Stairs = new ZevBlockStairs(ModBlocks.stone8, "stone8");
	public static Block stone9Stairs = new ZevBlockStairs(ModBlocks.stone9, "stone9");
	public static Block stone10Stairs = new ZevBlockStairs(ModBlocks.stone10, "stone10");
	public static Block stone11Stairs = new ZevBlockStairs(ModBlocks.stone11, "stone11");
	public static Block stone12Stairs = new ZevBlockStairs(ModBlocks.stone12, "stone12");
	public static Block sugarBlockStairs = new ZevBlockStairs(ModBlocks.sugarBlock, "sugarBlock");
	public static Block thatchStairs = new ZevBlockStairs(ModBlocks.thatch, "thatch");
	public static Block topazBlockStairs = new ZevBlockStairs(ModBlocks.topazBlock, "topazBlock");
	public static Block topazOreStairs = new ZevBlockStairs(ModBlocks.topazOre, "topazOre");
	public static Block woolStairs = new ZevBlockStairs(Blocks.wool, "wool");
	public static Block yellowStoneStairs = new ZevBlockStairs(ModBlocks.yellowStone, "yellowStone");
	public static Block yellowStone_smoothStairs = new ZevBlockStairs(ModBlocks.yellowStone_smooth, "yellowStone_smooth");

    public static Block redwood_planksStairs = new ZevBlockStairs(ModBlocks.redwood_planks, "redwood_planks");
    public static Block maple_planksStairs = new ZevBlockStairs(ModBlocks.maple_planks, "maple_planks");
    public static Block palm_planksStairs = new ZevBlockStairs(ModBlocks.palm_planks, "palm_planks");
    public static Block willow_planksStairs = new ZevBlockStairs(ModBlocks.willow_planks, "willow_planks");
    public static Block pine_planksStairs = new ZevBlockStairs(ModBlocks.pine_planks, "pine_planks");
    public static Block fir_planksStairs = new ZevBlockStairs(ModBlocks.fir_planks, "fir_planks");
    public static Block chestnut_planksStairs = new ZevBlockStairs(ModBlocks.chestnut_planks, "chestnut_planks");
    public static Block sequoia_planksStairs = new ZevBlockStairs(ModBlocks.sequoia_planks, "sequoia_planks");
    public static Block elm_planksStairs = new ZevBlockStairs(ModBlocks.elm_planks, "elm_planks");
    public static Block hickory_planksStairs = new ZevBlockStairs(ModBlocks.hickory_planks, "hickory_planks");
    public static Block cedar_planksStairs = new ZevBlockStairs(ModBlocks.cedar_planks, "cedar_planks");
    public static Block sycamore_planksStairs = new ZevBlockStairs(ModBlocks.sycamore_planks, "sycamore_planks");
    public static Block cypress_planksStairs = new ZevBlockStairs(ModBlocks.cypress_planks, "cypress_planks");
    public static Block eucalyptus_planksStairs = new ZevBlockStairs(ModBlocks.eucalyptus_planks, "eucalyptus_planks");
    public static Block mahogany_planksStairs = new ZevBlockStairs(ModBlocks.mahogany_planks, "mahogany_planks");
    public static Block magnolia_planksStairs = new ZevBlockStairs(ModBlocks.magnolia_planks, "magnolia_planks");

    public static void init()
	{	
		 RegisterHelper.registerBlock(adobeBlockStairs);
		 RegisterHelper.registerBlock(adobe_bricksStairs);
		 RegisterHelper.registerBlock(adobeTileStairs);
		 RegisterHelper.registerBlock(amethystBlockStairs);
		 RegisterHelper.registerBlock(amethystOreStairs);
		 RegisterHelper.registerBlock(andesiteStairs);
		 RegisterHelper.registerBlock(andesite_bricksStairs);
		 RegisterHelper.registerBlock(andesite_smoothStairs);
		 RegisterHelper.registerBlock(aquamarineBlockStairs);
		 RegisterHelper.registerBlock(aquaStoneStairs);
		 RegisterHelper.registerBlock(aquaStone_smoothStairs);
		 RegisterHelper.registerBlock(ashBlockStairs);
		 RegisterHelper.registerBlock(ashStoneStairs);
		 RegisterHelper.registerBlock(bambooThatchBlockStairs);
		 RegisterHelper.registerBlock(basaltStairs);
		 RegisterHelper.registerBlock(basalt_bricksStairs);
		 RegisterHelper.registerBlock(basalt_smoothStairs);
		 RegisterHelper.registerBlock(bedrockStairs);
		 RegisterHelper.registerBlock(blueStoneStairs);
		 RegisterHelper.registerBlock(blueStone_smoothStairs);
		 RegisterHelper.registerBlock(brownStoneStairs);
		 RegisterHelper.registerBlock(brownStone_smoothStairs);
		 RegisterHelper.registerBlock(cementBlockStairs);
		 RegisterHelper.registerBlock(charcoalBlockStairs);
		 RegisterHelper.registerBlock(chertStairs);
		 RegisterHelper.registerBlock(chert_bricksStairs);
		 RegisterHelper.registerBlock(chertPolishedBlockStairs);
		 RegisterHelper.registerBlock(chertCobbleStairs); 
		 RegisterHelper.registerBlock(clayStairs);
		 RegisterHelper.registerBlock(coalBlockStairs);
		 RegisterHelper.registerBlock(coarseDirtStairs);
		 RegisterHelper.registerBlock(crackedSandStairs);
		 RegisterHelper.registerBlock(cragRockStairs);
		 RegisterHelper.registerBlock(daciteStairs);
		 RegisterHelper.registerBlock(dacite_bricksStairs);
		 RegisterHelper.registerBlock(dacitePolishedBlockStairs);
		 RegisterHelper.registerBlock(daciteCobbleStairs); 
		 RegisterHelper.registerBlock(darkPrismarineStairs);
         RegisterHelper.registerBlock(darkQuartzBlockStairs);
		 RegisterHelper.registerBlock(diamondBlockStairs);
		 RegisterHelper.registerBlock(diamondOreStairs);
		 RegisterHelper.registerBlock(dioriteStairs);
		 RegisterHelper.registerBlock(diorite_bricksStairs);
		 RegisterHelper.registerBlock(diorite_smoothStairs);
		 RegisterHelper.registerBlock(dirtStairs);
		 RegisterHelper.registerBlock(driedDirtStairs);
		 RegisterHelper.registerBlock(emeraldBlockStairs);
		 RegisterHelper.registerBlock(emeraldOreStairs);
		 RegisterHelper.registerBlock(endStoneStairs);
		 RegisterHelper.registerBlock(endStoneBricksStairs);
		 RegisterHelper.registerBlock(gabbroStairs);
		 RegisterHelper.registerBlock(gabbro_bricksStairs);
		 RegisterHelper.registerBlock(gabbroPolishedBlockStairs);
		 RegisterHelper.registerBlock(gabbroCobbleStairs);
		 RegisterHelper.registerBlock(glowstoneStairs);
		 RegisterHelper.registerBlock(goldBlockStairs);
		 RegisterHelper.registerBlock(goldOreStairs);
		 RegisterHelper.registerBlock(gravelStairs);
		 RegisterHelper.registerBlock(graniteStairs);
		 RegisterHelper.registerBlock(granite_bricksStairs);
		 RegisterHelper.registerBlock(granite_smoothStairs);
		 RegisterHelper.registerBlock(graniteCobbleStairs);
		 RegisterHelper.registerBlock(greenStoneStairs);
		 RegisterHelper.registerBlock(greenStone_smoothStairs);
		 RegisterHelper.registerBlock(hardenedClayStairs);
		 RegisterHelper.registerBlock(hardenedDirtStairs);
		 RegisterHelper.registerBlock(hardenedSandStairs);
		 RegisterHelper.registerBlock(hardenedSandstoneStairs);
		 RegisterHelper.registerBlock(hardenedSandstone_bricksStairs);
		 RegisterHelper.registerBlock(hardenedSandstoneCobbleStairs);
		 RegisterHelper.registerBlock(hardenedSandstonePolishedBlockStairs);
		 RegisterHelper.registerBlock(hardenedIceStairs);
		 RegisterHelper.registerBlock(hayVariantStairs);
		 RegisterHelper.registerBlock(ironBlockStairs);
		 RegisterHelper.registerBlock(ironOreStairs);
		 RegisterHelper.registerBlock(lapisBlockStairs);
		 RegisterHelper.registerBlock(lapisOreStairs);
        RegisterHelper.registerBlock(limestoneStairs);
        RegisterHelper.registerBlock(limestone_bricksStairs);
        RegisterHelper.registerBlock(limestoneCobbleStairs);
        RegisterHelper.registerBlock(limestonePolishedBlockStairs);
         RegisterHelper.registerBlock(magmaBlockStairs);
         RegisterHelper.registerBlock(marbleStairs);
		 RegisterHelper.registerBlock(marble_bricksStairs);
		 RegisterHelper.registerBlock(marblePolishedBlockStairs);
		 RegisterHelper.registerBlock(marbleCobbleStairs);
		 RegisterHelper.registerBlock(melonBlockStairs);
		 RegisterHelper.registerBlock(mud_bricksStairs);
		 RegisterHelper.registerBlock(mudBlockStairs);
		 RegisterHelper.registerBlock(mushroomBlock1Stairs);
		 RegisterHelper.registerBlock(mushroomBlock2Stairs);
		 RegisterHelper.registerBlock(mushroomBlock3Stairs);
		 RegisterHelper.registerBlock(mushroomBlock4Stairs);
		 RegisterHelper.registerBlock(netherrackStairs);
         RegisterHelper.registerBlock(netherWartBlockStairs);
		 RegisterHelper.registerBlock(obsidianStairs);
		 RegisterHelper.registerBlock(obsidian_smoothStairs);
		 RegisterHelper.registerBlock(packedIceStairs);
		 RegisterHelper.registerBlock(pinkStoneStairs);
		 RegisterHelper.registerBlock(pinkStone_smoothStairs);
		 RegisterHelper.registerBlock(prismarine_bricksStairs);
		 RegisterHelper.registerBlock(quartzStoneStairs);
		 RegisterHelper.registerBlock(quartzStone_bricksStairs);
		 RegisterHelper.registerBlock(quartzStonePolishedBlockStairs);
		 RegisterHelper.registerBlock(quartzStoneCobbleStairs);
		 RegisterHelper.registerBlock(quickSandStairs);
		 RegisterHelper.registerBlock(redNetherBrickStairs);
		 RegisterHelper.registerBlock(redRockStairs);
		 RegisterHelper.registerBlock(redRock_bricksStairs);
		 RegisterHelper.registerBlock(redRockCobbleStairs);
		 RegisterHelper.registerBlock(redRockTileStairs);
		 RegisterHelper.registerBlock(redstoneBlockStairs);
		 RegisterHelper.registerBlock(rhyoliteStairs);
		 RegisterHelper.registerBlock(rhyolite_bricksStairs);
		 RegisterHelper.registerBlock(rhyolitePolishedBlockStairs);
		 RegisterHelper.registerBlock(rhyoliteCobbleStairs);
		 RegisterHelper.registerBlock(rubyBlockStairs);
		 RegisterHelper.registerBlock(rubyOreStairs);
		 RegisterHelper.registerBlock(sandCoarseDirtStairs);
		 RegisterHelper.registerBlock(sandDirtStairs);
		 RegisterHelper.registerBlock(sapphireBlockStairs);
		 RegisterHelper.registerBlock(sapphireOreStairs);
		 RegisterHelper.registerBlock(schistStairs);
		 RegisterHelper.registerBlock(schist_bricksStairs);
		 RegisterHelper.registerBlock(schistCobbleStairs);
		 RegisterHelper.registerBlock(schistPolishedBlockStairs);
		 RegisterHelper.registerBlock(shaleStairs);
		 RegisterHelper.registerBlock(shale_bricksStairs);
		 RegisterHelper.registerBlock(shalePolishedBlockStairs);
		 RegisterHelper.registerBlock(shale_smoothStairs);
		 RegisterHelper.registerBlock(shaleCobbleStairs);
		 RegisterHelper.registerBlock(siltStoneStairs);
		 RegisterHelper.registerBlock(siltStone_smoothStairs);
		 RegisterHelper.registerBlock(silverOreStairs);
		 RegisterHelper.registerBlock(stoneChalkStairs);
		 RegisterHelper.registerBlock(stoneChalk_bricksStairs);
		 RegisterHelper.registerBlock(stoneChalkPolishedBlockStairs);
		 RegisterHelper.registerBlock(stoneChalkCobbleStairs);
		 RegisterHelper.registerBlock(slateStairs);
		 RegisterHelper.registerBlock(slate_bricksStairs);
		 RegisterHelper.registerBlock(slateCobbleStairs);
		 RegisterHelper.registerBlock(smoothStoneStairs);
		 RegisterHelper.registerBlock(snowStairs);
		 RegisterHelper.registerBlock(soulSandStairs);
		 RegisterHelper.registerBlock(spongeStairs);
		 RegisterHelper.registerBlock(stone1Stairs);
		 RegisterHelper.registerBlock(stone2Stairs);
		 RegisterHelper.registerBlock(stone3Stairs);
		 RegisterHelper.registerBlock(stone4Stairs);
		 RegisterHelper.registerBlock(stone5Stairs);
		 RegisterHelper.registerBlock(stone6Stairs);
		 RegisterHelper.registerBlock(stone7Stairs);
		 RegisterHelper.registerBlock(stone8Stairs);
		 RegisterHelper.registerBlock(stone9Stairs);
		 RegisterHelper.registerBlock(stone10Stairs);
		 RegisterHelper.registerBlock(stone11Stairs);
		 RegisterHelper.registerBlock(stone12Stairs);

		 RegisterHelper.registerBlock(sugarBlockStairs);
		 RegisterHelper.registerBlock(thatchStairs);
		 RegisterHelper.registerBlock(topazOreStairs);
		 RegisterHelper.registerBlock(woolStairs);
		 RegisterHelper.registerBlock(yellowStoneStairs);
		 RegisterHelper.registerBlock(yellowStone_smoothStairs);
		 RegisterHelper.registerBlock(boneBlockStairs);
		 RegisterHelper.registerBlock(bonemealBlockStairs);
		 RegisterHelper.registerBlock(blazeBlockStairs);
		 RegisterHelper.registerBlock(enderPearlBlockStairs);
		 RegisterHelper.registerBlock(flintBlockStairs);
		 RegisterHelper.registerBlock(gunpowderBlockStairs);
		 RegisterHelper.registerBlock(rottenFleshBlockStairs);
		 RegisterHelper.registerBlock(silverBlockStairs);	
		 RegisterHelper.registerBlock(topazBlockStairs);

        RegisterHelper.registerBlock(redwood_planksStairs);
        RegisterHelper.registerBlock(maple_planksStairs);
        RegisterHelper.registerBlock(palm_planksStairs);
        RegisterHelper.registerBlock(willow_planksStairs);
        RegisterHelper.registerBlock(pine_planksStairs);
        RegisterHelper.registerBlock(fir_planksStairs);
        RegisterHelper.registerBlock(chestnut_planksStairs);
        RegisterHelper.registerBlock(sequoia_planksStairs);
        RegisterHelper.registerBlock(elm_planksStairs);
        RegisterHelper.registerBlock(hickory_planksStairs);
        RegisterHelper.registerBlock(cedar_planksStairs);
        RegisterHelper.registerBlock(sycamore_planksStairs);
        RegisterHelper.registerBlock(cypress_planksStairs);
        RegisterHelper.registerBlock(eucalyptus_planksStairs);
        RegisterHelper.registerBlock(mahogany_planksStairs);
        RegisterHelper.registerBlock(magnolia_planksStairs);

    }
}